name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  deployments: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Build
      run: yarn build
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: nextjs-build
        path: .next/
        
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: .next/
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2

    - name: Create deployment
      uses: actions/github-script@v6
      with:
        script: |
          try {
            await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              environment: 'production',
              auto_merge: false,
              required_contexts: [],
              description: 'Deployment from GitHub Actions'
            });
          } catch (error) {
            console.error('Deployment creation failed:', error);
            // Don't fail the workflow if deployment creation fails
            process.exit(0);
          } 